/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.github.hzhang.router.plugin

import com.android.build.gradle.AppExtension
import com.github.hzhang.router.plugin.log.Loger
import com.github.hzhang.router.plugin.transform.RouteTransform
import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
public class RouterPlugin implements Plugin<Project> {
    private static final String TAG = "RouterPlugin"

    void apply(Project project) {
        init(project)
        AppExtension android = project.extensions.getByType(AppExtension)
        android.registerTransform(new RouteTransform(project))
    }

    private static void init(Project proj) {
        Loger.PROJ = proj
    }
}
